name = "panda-photo-contest-api"
compatibility_date = "2026-02-17"

# 关键：Pages 必须有这个，用来指定静态产物目录
pages_build_output_dir = "dist"

# 绑定 D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "panda-db"
database_id = "db456420-c2cd-4d53-8bdb-320c780137c9"

# 绑定 R2 存储桶
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "panda-assets"
